# Starship Prompt Configuration
# Guide for configuration at https://starship.rs/config/

# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 10000

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[](bold green)"     # The "success_symbol" segment is being set to "" with the color "bold green"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold green)"

[username]
show_always = true
style_user = "bold blue"

[git_branch]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = '%r'

[custom.drupal]
command = "echo -n $( grep -A1 '\"name\": \"drupal/core\"' composer.lock | awk '{ print $2 }' | tail -1 | sed 's/[^0-9.]*//g' )"
files = ["composer.lock"]
directories = ["web/core"]
format = "via [](bold cyan) [v$output](bold cyan) "
